apiVersion: v1
kind: Pod
metadata:
  name: statuspage
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  containers:
  - image: statuspage-web
    name: web
    resources: {}
  - image: statuspage-api
    name: api
    resources: {}
    envFrom:
    - secretRef:
        name: api-env
  - image: caddy:latest
    name: caddy
    resources: {}
    command:
    - sh
    - -c
    - |
        cat > Caddyfile <<EOF
        :5000
        handle_path /api/* {
            reverse_proxy /* localhost:4000
        }
        reverse_proxy /* localhost:3000
        EOF
        exec caddy run